!
! Set this in /etc/frr/daemons file:
! ospfd=yes
! ospfd_instances=1
!
! Network map:
!
! [Cross-border WAN]    [Domestic WAN]
!         ^                   ^
!         |                   |
!       SNAT      GRE       SNAT  GRE over IPsec
!       [R3] <------------- [R2] <============== [R1]
!              OSPF routes             0/0
!
!     Foreign             Domestic            Home/Office
!     router               router               router
!
! EXAMPLE /etc/frr/frr.conf
!
hostname r3.router
log syslog notifications
no ipv6 forwarding
!
interface dummy0
 ip ospf 1 area 0.0.0.0
exit
!
interface tun-r2
 ip ospf 1 area 0.0.0.0
 ip ospf authentication message-digest
 ip ospf dead-interval 40
 ip ospf hello-interval 2
 ip ospf message-digest-key 1 md5 XXXXXXXX
 no ip ospf passive
exit
!
router ospf 1
 ospf router-id 172.16.0.1
 redistribute kernel route-map STATIC
 passive-interface default
 area 0.0.0.0 authentication message-digest
exit
!
route-map STATIC permit 10
 match metric 123
exit
!
end
